### ISSUE TITLE
update menu

### ISSUE THREAD

**Issue by hamzah11401** [deluxewolf/eatoutmoreoften#4]
The team needs to update the menu item with the right prices and the right items on the menu. so the customer has the same prices on the website and the app.

**Comment by hamzah11401** [comment]
[Eat Out More Often (Menu Items) (1) (1).docx](https://github.com/deluxewolf/eatoutmoreoften/files/6518430/Eat.Out.More.Often.Menu.Items.1.1.docx)

**Comment by deluxewolf** [comment]
The menu prices now seem to be correct on both solutions
